logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
server:
  port: 8090
spring:
  rabbitmq:
    host: localhost #本机的虚拟ip
    port: 5672 #端口号
    username: hmall
    virtual-host: /hmall
    password: 12345678
    connection-timeout: 1s #设置连接超时时间
    template:
      retry: #生产者端开启重连重试机制
        enabled: true
        initial-interval: 1000ms #失败后等待时间
        multiplier: 1 # 失败后下次等待的时长的倍数
        max-attempts: 3 # 最多尝试的次数
    publisher-confirm-type: correlated # 生产者确认机制
    publisher-returns: true # return
