logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
server:
  port: 8090
spring:
  rabbitmq:
    host: 192.168.1.10 #本机的虚拟ip
    port: 5672 #端口号
    username: hmall
    virtual-host: /hmall
    password: 12345678
