logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
server:
  port: 8091

spring:
  rabbitmq:
    host: localhost #本机的虚拟ip
    port: 5672 #端口号
    username: hmall
    virtual-host: /hmall
    password: 12345678
    listener:
      simple:
        prefetch: 1 # 能者多劳
        acknowledge-mode: auto #消费者消息确认机制开启，自动
        retry: #消费者开启消息重试机制：
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: true # true无状态，false是有状态